Buddy mlir integration
sequencer/vector pull request #140
Opened 2023-02-28 11:50 UTC by ksco

2023-02-28 12:24 UTC, sequencer commented on build.sc
> +    object buddy extends Case {
```suggestion
    object buddy extends Cross[BuddyMLIRCase]("hello.mlir") 
    class BuddyMLIRCase(mlirSourceFile: String) extends Case {
```

2023-03-01 03:00 UTC, sequencer requested changes
Please detect case based on file name

2023-03-01 03:49 UTC, sequencer submitted a review, later dismissed

2023-03-01 07:20 UTC, qinjun-li approved these changes

2023-03-01 07:20 UTC, merged