[cosim] Fix mem write
sequencer/vector pull request #165
Opened 2023-03-14 06:40 UTC by ksco

2023-03-14 12:08 UTC, SharzyL requested changes

2023-03-14 12:08 UTC, SharzyL commented on tests/emulator/src/spike_event.h
> +      int index = 0;
use a meaningful name, e.g. `num_completed_writes`

2023-03-14 14:05 UTC, ksco commented on tests/emulator/src/spike_event.h
> +      int index = 0;
Updated, please review again.

2023-03-15 03:21 UTC, SharzyL approved these changes

2023-03-15 03:21 UTC, merged